sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 101.201.65.241
    port: 3306
    database: Blossom
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret:
    access-key-id:
    bucket-name: blossom-server
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wxa91ba8ae90d0cf2d
    secret: 60d0618ecd57c7557080f610e4645a1e
