sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 101.201.65.241
    port: 3978
    database: blossom
    username: root
    password: "@LHbyzhwl7794"
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret:
    access-key-id:
    bucket-name: blossom-server
  redis:
    host: 101.201.65.241
    password: 'v123456'
    port: 6379
  wechat:
    appid: wxa91ba8ae90d0cf2d
    secret: 60d0618ecd57c7557080f610e4645a1e
